version: '3.8'

services:
  # Django web application service
  web:
    image: your_docker_image_name  # Replace with the name of your Django Docker image
    container_name: your_container_name  # Replace with a suitable container name
    restart: always
    ports:
      - "8000:8000"  # Expose port 8000 on the host
    env_file:
      - .env  # Load environment variables from the .env file
    volumes:
      - ./project:/code  # Mount the project directory to the container
    depends_on:
      - db  # Depend on the PostgreSQL database service

  # PostgreSQL database service
  db:
    image: postgres:latest
    container_name: db_container
    restart: always
    ports:
      - "5432:5432"  # Expose port 5432 on the host
    environment:
      POSTGRES_DB: your_db_name  # Replace with your database name
      POSTGRES_USER: your_db_user  # Replace with your database username
      POSTGRES_PASSWORD: your_db_password  # Replace with your database password
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data

volumes:
  db_data:  # Volume for persisting database data
